name: Reusable WF - Release

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:

  build-test-package:
    uses: "./.github/workflows/build-test-package.yml"
    secrets: inherit
    with:
      version: ${{ inputs.version }}

  create-release:
    needs: ['build-test-package']
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      contents: write
      id-token: write

    steps:

      - uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./tmp

      - name: Clean up dir
        run: |
          mkdir -p dist
          find ./tmp -type f -name '*.whl' -exec mv -t ./dist {} +
          find ./tmp -type f -name '*.tar.gz' -exec mv -t ./dist {} +
          ls ./dist

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ inputs.version }}
          commit: ${{ github.sha }}
          name: "amalgam-lang-py ${{ inputs.version }}"
          artifactErrorsFailBuild: true
          generateReleaseNotes: true
          makeLatest: legacy
          artifacts: "dist/*"
          artifactContentType: application/gzip

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1